#!/usr/bin/env python3
"""Writes the GENERATED block of tests/suite/85_datetime_round2.bas: every
expected value below comes from Python's proleptic Gregorian `datetime` and
from integer arithmetic, never from a run of Phosphor.

WHY IT EXISTS (2026-10-09, round 2 of the adversarial loop). A TDateTime before
1899-12-30 is negative and FPC spells it SIGN-AND-MAGNITUDE: the date is
Trunc(d) and the time of day Abs(Frac(d)), so noon on 1850-06-15 is -18095.5
where midnight is -18095. DateUtils' arithmetic is written for the positive
half and patched at the epoch (MaybeSkipTimeWarp), and the patch is wrong:
incday and incweek moved a midnight one day too far across 1899-12-30,
weekoftheyear answered the previous ISO week for a pre-1900 Monday carrying a
time of day, and the finer increments took their step through a 32-bit
narrowing. Three rounds had each found ONE more of these by thinking of a
case; this sweep stops thinking of cases (docs/proof-axes.md rule 0.1: a
sweep is GENERATED, not chosen).

THE MODEL the expectations are computed in: an instant is (D, ms) -- D the
signed count of days from 1899-12-30, ms the milliseconds into that day,
0..86399999. That is a LINEAR scale: moving by a step is integer addition on
D*86400000 + ms. The TDateTime the library holds is D + ms/86400000 when
D >= 0 and D - ms/86400000 when D < 0; the .bas builds it with `mk`, which
says exactly that, beside the assertions.

THE GRID (seeded, so every run asks the same questions):
  * calendar: every day from 250 before the epoch to 250 after it, the first
    and last 20 days of 0001..9999, the turn of 14 chosen years (1, 4, 100,
    1582, 1600, 1752, 1850, 1899, 1900, 1904, 2000, 2024, 4000, 9998) and 120
    days drawn uniformly over the whole range; each at a time of day taken in
    turn from midnight, 1 ms, 06:00, noon, 23:59:59.999 and a random one.
    Checked: weekoftheyear/weekof (Python's isocalendar), weekofthemonth (the
    week, Monday to Sunday, belongs to the month holding its Thursday -- the
    rule DateUtils.DecodeDateMonthWeek implements), dayoftheweek, dayofweek,
    dayoftheyear, weeksinyear (the ISO week of 28 December), daysinmonth,
    daysinyear, and the decomposition yearof..millisecondof.
  * increments: incday, incweek, inchour, incminute, incsecond and
    incmillisecond from instants near the epoch, near both ends and at
    random, by small steps, by the steps that land one day either side of
    1899-12-30 and on it, by +-2^31-1, +-2^31, +-2^31+1, 2^32, and by the
    largest steps that stay inside 0001..9999; and from a few starts, by
    steps far outside it (1e15, 2^62, 2^63, 1e300), whose answer is the
    plain sum -- outside the calendar, but not clipped at any width.
  * incmonth and incyear: the day CLAMPED onto a shorter month (the rule
    date-time.md states), the time carried, and a step that leaves
    0001..9999 refused.
  * distances: millisecondsbetween .. weeksbetween and dayspan over pairs of
    those instants, from the exact millisecond difference.
  * text: datetimetostr$ against Python's isoformat(" ") (the date alone at
    midnight, as the page documents) and strtodatetime back to the same
    number.

Usage: datetime_round2_sweep.py         rewrites the block in place
       datetime_round2_sweep.py --check exits 1 if the file is not what this
                                        script would write
"""
import calendar
import datetime as dt
import math
import random
import sys
from fractions import Fraction
from pathlib import Path

MSD = 86400000
EPOCH = dt.date(1899, 12, 30)
FIRST = (dt.date(1, 1, 1) - EPOCH).days
LAST = (dt.date(9999, 12, 31) - EPOCH).days
SEED = 20261009
BAS = Path(__file__).resolve().parent / 'suite' / '85_datetime_round2.bas'
BEGIN = 'rem --- BEGIN GENERATED by tests/datetime_round2_sweep.py: do not edit by hand ---'
END = 'rem --- END GENERATED ---'

rng = random.Random(SEED)


def day_of(D):
    return EPOCH + dt.timedelta(days=D)


def stamp(D, ms):
    return dt.datetime.combine(day_of(D), dt.time()) + dt.timedelta(milliseconds=ms)


def iso_week(d):
    return d.isocalendar()[1]


def week_of_month(d):
    thursday = d + dt.timedelta(days=4 - d.isoweekday())
    return (thursday.day - 1) // 7 + 1


def days_in_month(y, m):
    return calendar.monthrange(y, m)[1]


def leap(y):
    return y % 4 == 0 and (y % 100 != 0 or y % 400 == 0)


def times_cycle(i):
    k = i % 6
    if k == 0: return 0
    if k == 1: return 1
    if k == 2: return 21600000
    if k == 3: return 43200000
    if k == 4: return MSD - 1
    return rng.randrange(MSD)


def calendar_instants():
    days = list(range(-200, 201))
    days += list(range(FIRST, FIRST + 20)) + list(range(LAST - 19, LAST + 1))
    for y in (1, 4, 100, 1582, 1600, 1752, 1850, 1899, 1900, 1904, 2000, 2024, 4000, 9998):
        base = (dt.date(y, 12, 31) - EPOCH).days
        days += [x for x in range(base - 6, base + 8) if FIRST <= x <= LAST]
    days += [rng.randint(FIRST, LAST) for _ in range(120)]
    seen = set()
    out = []
    for i, D in enumerate(days):
        ms = times_cycle(i)
        if (D, ms) in seen:
            continue
        seen.add((D, ms))
        out.append((D, ms))
    return out


def fractional_instants():
    """Moments that are NOT on the millisecond grid, within half a millisecond
    of one: every renderer and every decomposition reads a date to the
    millisecond, rounding half up ON THE LINE, so 23:59:59.9997 is the next
    day's midnight on both sides of the epoch."""
    out = []
    for D in list(range(-30, 31, 2)) + [FIRST, FIRST + 1, LAST - 2, LAST - 1]:
        for ms in ('86399999.7', '0.3', '43199999.6'):
            out.append((D, ms))
    return out


def calendar_line(D, ms):
    if isinstance(ms, str):
        total = D * MSD + Fraction(ms)
        rD, rms = split(math.floor(total + Fraction(1, 2)))    # half up, on the line
        return calendar_line(rD, rms).replace(f'c({rD}, {rms},', f'c({D}, {ms},', 1)
    d = day_of(D)
    s = stamp(D, ms)
    sig = (((iso_week(d) * 10 + week_of_month(d)) * 10 + d.isoweekday()) * 1000
           + d.timetuple().tm_yday) * 100 + iso_week(dt.date(d.year, 12, 28))
    sig2 = ((d.isoweekday() % 7 + 1) * 100 + days_in_month(d.year, d.month)) * 1000 \
        + (366 if leap(d.year) else 365)
    ymd = d.year * 10000 + d.month * 100 + d.day
    hms = s.hour * 10000000 + s.minute * 100000 + s.second * 1000 + s.microsecond // 1000
    return f'c({D}, {ms}, {sig}, {sig2}, {ymd}, {hms})'


UNITS = [(1, MSD), (2, 7 * MSD), (3, 3600000), (4, 60000), (5, 1000), (6, 1)]


def split(total):
    return total // MSD, total % MSD


def in_range(total):
    return FIRST * MSD <= total <= LAST * MSD + MSD - 1


def inc_starts():
    starts = []
    for D in (-3, -1, 0, 1, 3, -8):
        for ms in (0, 43200000, rng.randrange(MSD)):
            starts.append((D, ms))
    starts += [(FIRST, 0), (FIRST, MSD - 1), (LAST, 0), (LAST, MSD - 1)]
    for _ in range(4):
        starts.append((rng.randint(FIRST, LAST), rng.randrange(MSD)))
    return starts


def inc_lines():
    lines = []
    starts = inc_starts()
    for u, U in UNITS:
        for idx, (D, ms) in enumerate(starts):
            t0 = D * MSD + ms
            steps = [1, -1, 7, -30]
            # the steps that land one day either side of the epoch, and on it
            for target in (-1, 0, 1):
                n = (target * MSD + rng.randrange(MSD) - t0) // U if U < MSD else (target - D) * MSD // U
                steps.append(n)
            if idx % 4 == 0:
                steps += [2**31 - 1, 2**31, 2**31 + 1, -(2**31), -(2**31) - 1, 2**32]
                steps.append((LAST * MSD + MSD - 1 - t0) // U)        # largest step inside
                steps.append(-((t0 - FIRST * MSD) // U))              # largest step back inside
            for n in steps:
                total = t0 + n * U
                if in_range(total):
                    eD, ems = split(total)
                    # Python's own calendar agrees with the integer arithmetic
                    assert stamp(D, ms) + dt.timedelta(milliseconds=n * U) == stamp(eD, ems)
                    lines.append(f'k({u}, {D}, {ms}, {n}, {eD}, {ems})')
                else:
                    lines.append(far_line(u, D, ms, n, U))
            if idx % 9 == 0:
                for n in (10**15, -(10**15), 2**62, -(2**62), 2**63, -(2**63), 10**300):
                    lines.append(far_line(u, D, ms, n, U))
    return lines


def far_line(u, D, ms, n, U):
    """A step that leaves the calendar: the answer is the plain sum, as a
    sign-and-magnitude number, never a step clipped to some width."""
    total = Fraction(D * MSD + ms) + Fraction(n) * U
    eD = total // MSD
    efrac = (total - eD * MSD) / MSD
    e = float(eD + efrac) if eD >= 0 else float(eD - efrac)
    ns = repr(float(n)) if abs(n) >= 2**53 else str(n)
    return f'kx({u}, {D}, {ms}, {ns}, {e!r})'


def add_months(d, n):
    tot = d.year * 12 + (d.month - 1) + n
    y, m = tot // 12, tot % 12 + 1
    if y < 1 or y > 9999:
        return None
    return dt.date(y, m, min(d.day, days_in_month(y, m)))


def month_lines():
    lines = []
    starts = []
    for y, m, dd in ((1899, 12, 30), (1899, 12, 31), (1900, 1, 31), (1899, 11, 30),
                     (1850, 6, 15), (1600, 2, 29), (2024, 1, 31), (2024, 2, 29),
                     (1, 1, 1), (1, 3, 31), (9999, 12, 31), (9999, 1, 31), (1899, 1, 31)):
        D = (dt.date(y, m, dd) - EPOCH).days
        starts += [(D, 0), (D, rng.randrange(MSD))]
    for _ in range(3):
        starts.append((rng.randint(FIRST, LAST), rng.randrange(MSD)))
    for D, ms in starts:
        d = day_of(D)
        for u, steps in ((7, [1, -1, 11, -13, 25, -1201, 119987, -119987,
                              2**31, -(2**31) - 5]),
                         (8, [1, -1, 4, -101, 9998, -(2**31)])):
            for n in steps:
                r = add_months(d, n if u == 7 else 12 * n)
                # The step runs at the TOP LEVEL, where the trap armed around
                # this block can catch it (a label belongs to the program,
                # never to a function), and `mo` judges it and clears `rf`.
                fn = 'incmonth' if u == 7 else 'incyear'
                lines.append(f'r = {fn}(mk({D}, {ms}), {n})')
                if r is None:
                    lines.append(f'mo({u}, {D}, {ms}, {n}, 0, -1)')
                else:
                    lines.append(f'mo({u}, {D}, {ms}, {n}, {(r - EPOCH).days}, {ms})')
    return lines


def pair_lines(instants):
    lines = []
    near = [p for p in instants if -40 <= p[0] <= 40]
    for _ in range(120):
        a, b = rng.choice(near), rng.choice(instants)
        if rng.random() < 0.5:
            b = rng.choice(near)
        delta = abs((a[0] * MSD + a[1]) - (b[0] * MSD + b[1]))
        lines.append(f'p({a[0]}, {a[1]}, {b[0]}, {b[1]}, {delta})')
    return lines


def text_lines(instants):
    lines = []
    for D, ms in instants[::5]:
        ms = ms - ms % 1000                       # the text carries whole seconds
        s = stamp(D, ms)
        t = s.date().isoformat() if ms == 0 else s.isoformat(' ')
        lines.append(f'tx({D}, {ms}, "{t}")')
    return lines


def block():
    inst = calendar_instants()
    cal = [calendar_line(D, ms) for D, ms in inst + fractional_instants()]
    inc = inc_lines()
    mon = month_lines()
    pairs = pair_lines(inst)
    texts = text_lines(inst)
    out = [BEGIN]
    # The counts are the generator's, so a case that silently did not run --
    # an error that skipped it, a truncated file -- is a failure.
    out += [f'want_c = {len(cal)}', f'want_k = {len(inc)}',
            f'want_m = {sum(1 for x in mon if x.startswith("mo("))}',
            f'want_p = {len(pairs)}', f'want_t = {len(texts)}']
    out += cal + inc + ['rf = 0', 'on error goto refused'] + mon + ['on error goto 0'] + pairs + texts
    out.append(END)
    return out


def main(argv):
    if argv not in ([], ['--check']):
        print('usage: datetime_round2_sweep.py [--check]', file=sys.stderr)
        return 2
    text = BAS.read_text(encoding='utf-8')
    head, rest = text.split(BEGIN + '\n', 1)
    _, tail = rest.split(END + '\n', 1)
    new = head + '\n'.join(block()) + '\n' + tail
    if argv == ['--check']:
        return 0 if new == text else 1
    BAS.write_text(new, encoding='utf-8', newline='\n')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
