rem ---------------------------------------------------------------
rem The controls docs/gui-components.md named and nobody built.
rem
rem Sixteen in-scope items were missing when the plan was audited against
rem the registry. These are the ones with a constructor: radiogroup@,
rem checkgroup@, popupmenu@, tabcontrol@, imagelist@, trayicon@,
rem paintbox@, idletimer@, fontdialog@ -- plus the backbone helpers
rem control_parent@ / anchors / tabstop / taborder / spacing /
rem constraints, which the page listed and the code never had.
rem
rem What is MODAL is configured here and executed only by the interactive
rem host: fontdialog@'s Execute blocks, and inputbox$ blocks, so a
rem headless suite that ran them would hang. That is the same line the
rem dialog package already draws, not a new exception.
rem ---------------------------------------------------------------

f@ = form@("controls", 500, 400)

test_case("radiogroup/one answer out of several, base-1 like everything else")
gui_clearerror()
rg@ = radiogroup@(f@, "Size")
assert_eq(gui_error(), 0, "the constructor works")
assert_eq(radiogroup_caption$(rg@), "Size", "the caption came from the constructor")
radiogroup_add@(rg@, "small")
radiogroup_add@(rg@, "medium")
radiogroup_add@(rg@, "large")
assert_eq(radiogroup_count(rg@), 3, "three choices")
assert_eq(radiogroup_item$(rg@, 1), "small", "item 1 is the first, not the second")
assert_eq(radiogroup_item$(rg@, 3), "large", "and item 3 the last")
assert_eq(radiogroup_itemindex(rg@), 0, "nothing chosen yet is 0, not -1")
radiogroup_itemindex@(rg@, 2)
assert_eq(radiogroup_itemindex(rg@), 2, "choosing reads back base-1")
assert_eq(radiogroup_item$(rg@, radiogroup_itemindex(rg@)), "medium", "and indexes the right item")
radiogroup_clear@(rg@)
assert_eq(radiogroup_count(rg@), 0, "clear empties it")

test_case("checkgroup/one answer PER item")
cg@ = checkgroup@(f@, "Toppings")
checkgroup_add@(cg@, "cheese")
checkgroup_add@(cg@, "olives")
assert_eq(checkgroup_count(cg@), 2, "two items")
assert_eq(checkgroup_checked(cg@, 1), 0, "nothing ticked to begin with")
checkgroup_checked@(cg@, 1, 1)
assert_eq(checkgroup_checked(cg@, 1), 1, "the first is ticked")
assert_eq(checkgroup_checked(cg@, 2), 0, "and the second is not -- they are independent")
gui_clearerror()
z% = checkgroup_checked(cg@, 99)
assert_true(gui_error(), "an index past the end is recorded, not answered as unticked")

test_case("popupmenu/a context menu belongs to the control it pops up on")
rem PopupMenu is object-typed, so control_set@ cannot reach it -- attaching is
rem what the constructor exists for.
b@ = button@(f@)
gui_clearerror()
pm@ = popupmenu@(b@)
assert_eq(gui_error(), 0, "created and attached in one call")
gui_clearerror()
mi@ = menuitem@(pm@, "Copy")
assert_eq(gui_error(), 0, "a menu item can hang off a popup, not only a main menu")
assert_eq(menuitem_caption$(mi@), "Copy", "with its caption")
b2@ = button@(f@)
gui_clearerror()
popupmenu_attach@(pm@, b2@)
assert_eq(gui_error(), 0, "and one menu can serve a second control")

test_case("tabcontrol/tabs without a page each")
tc@ = tabcontrol@(f@)
tabcontrol_add@(tc@, "one")
tabcontrol_add@(tc@, "two")
assert_eq(tabcontrol_count(tc@), 2, "two tabs")
assert_eq(tabcontrol_tab$(tc@, 2), "two", "read back base-1")
tabcontrol_tabindex@(tc@, 2)
assert_eq(tabcontrol_tabindex(tc@), 2, "and the selection is base-1 too")
tabcontrol_clear@(tc@)
assert_eq(tabcontrol_count(tc@), 0, "cleared")

test_case("imagelist/a shared strip of icons, and what may point at it")
gui_clearerror()
il@ = imagelist@(16, 16)
assert_eq(gui_error(), 0, "constructed at a size")
assert_eq(imagelist_count(il@), 0, "empty to start")
bm@ = bitmap@(16, 16)
canvas_brushcolor@(bm@, 255)
canvas_fillrect@(bm@, 0, 0, 16, 16)
assert_eq(imagelist_addbitmap(il@, bm@), 1, "adding answers the index it took")
assert_eq(imagelist_count(il@), 1, "and the count follows")
tb@ = toolbar@(f@)
gui_clearerror()
imagelist_attach@(il@, tb@)
assert_eq(gui_error(), 0, "a toolbar takes an image list")
gui_clearerror()
imagelist_attach@(il@, b@)
assert_true(gui_error(), "a plain button does not")
gui_clearerror()
z% = imagelist_addfile(il@, "no_such_picture_file.png")
assert_true(gui_error(), "a missing file is an answer, not an exception")
assert_eq(imagelist_count(il@), 1, "and nothing was added")

test_case("paintbox/a live surface, drawn on with the same canvas calls")
gui_clearerror()
pb@ = paintbox@(f@)
assert_eq(gui_error(), 0, "constructed")
control_bounds@(pb@, 0, 0, 120, 80)
rem the point of generalising the canvas target: the identical calls that draw
rem onto an off-screen bitmap@ draw onto this
gui_clearerror()
canvas_pencolor@(pb@, 255)
canvas_moveto@(pb@, 0, 0)
canvas_lineto@(pb@, 100, 60)
canvas_rectangle@(pb@, 5, 5, 40, 30)
assert_eq(gui_error(), 0, "drawing on a paint box records no error")

test_case("canvas/the primitives the plan named and the canvas lacked")
assert_eq(bitmap_width(bm@), 16, "the bitmap is still the target it always was")
gui_clearerror()
canvas_line@(bm@, 0, 0, 15, 15)
canvas_roundrect@(bm@, 1, 1, 14, 14, 4, 4)
canvas_arc@(bm@, 0, 0, 15, 15, 0, 90)
canvas_pie@(bm@, 0, 0, 15, 15, 0, 90)
assert_eq(gui_error(), 0, "arc and pie take DEGREES, not the LCL's sixteenths")
canvas_polyline@(bm@, "0,0 5,5 10,0")
canvas_polygon@(bm@, "0,0 8,0 4,8")
assert_eq(gui_error(), 0, "points are 'x,y x,y x,y'")
gui_clearerror()
canvas_polygon@(bm@, "garbage")
assert_true(gui_error(), "a malformed point list is refused, not drawn with a stray vertex")
gui_clearerror()
canvas_polygon@(bm@, "1,1")
assert_true(gui_error(), "and one point is not a shape")
assert_true(canvas_textwidth(bm@, "hello") > 0, "text measures")
assert_true(canvas_textheight(bm@, "hello") > 0, "in both directions")

test_case("idletimer/a sibling of timer@, sharing every helper")
gui_clearerror()
it@ = idletimer@()
assert_eq(gui_error(), 0, "constructed")
timer_interval@(it@, 250)
assert_eq(timer_interval(it@), 250, "the timer helpers accept it -- they resolve the common base, not TTimer")
assert_eq(timer_enabled(it@), 0, "it starts stopped, like timer@")
timer_start@(it@)
assert_eq(timer_enabled(it@), 1, "and starts on request")
timer_stop@(it@)
assert_eq(timer_enabled(it@), 0, "and stops")

test_case("fontdialog/configured here, executed by the interactive host")
gui_clearerror()
fd@ = fontdialog@()
assert_eq(gui_error(), 0, "constructed")
fontdialog_fontname@(fd@, "Courier New")
fontdialog_fontsize@(fd@, 14)
assert_eq(fontdialog_fontname$(fd@), "Courier New", "the preselected face reads back")
assert_eq(fontdialog_fontsize(fd@), 14, "and the size")
dialog_title@(fd@, "Pick a font")
assert_eq(dialog_title$(fd@), "Pick a font", "and it shares the common-dialog surface")

test_case("backbone/the four helpers the page listed and the code never had")
gui_clearerror()
control_parent@(b2@, tc@)
assert_eq(gui_error(), 0, "a control can be re-parented -- the one thing the bridge cannot do")
control_anchors@(b@, "akLeft,akRight")
assert_eq(control_anchors$(b@), "akLeft,akRight", "anchors round-trip as identifiers")
control_tabstop@(b@, 1)
assert_eq(control_tabstop(b@), 1, "tabstop")
control_taborder@(b@, 0)
assert_eq(control_taborder(b@), 0, "taborder")
control_spacing@(b@, 6)
assert_eq(control_spacing(b@), 6, "BorderSpacing.Around -- class-typed, so no bridge reaches it")
control_minwidth@(b@, 40)
control_maxwidth@(b@, 200)
assert_eq(control_minwidth(b@), 40, "Constraints.MinWidth, likewise")
assert_eq(control_maxwidth(b@), 200, "and MaxWidth")

test_case("trayicon/configured headless; clicking needs a message loop")
gui_clearerror()
ti@ = trayicon@()
assert_eq(gui_error(), 0, "constructed")
trayicon_hint@(ti@, "Phosphor")
assert_eq(trayicon_hint$(ti@), "Phosphor", "its tooltip")
assert_eq(trayicon_visible(ti@), 0, "not shown until asked")
